// filepath: frontend/src/app/layout.tsx
import type { Metadata } from "next";
import { headers } from 'next/headers';
// import { Geist, Geist_Mono } from "next/font/google";
import '@fontsource/geist/400.css';
import '@fontsource/geist/700.css';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const nonce = (await headers()).get('x-nonce') ?? '';

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // Si usas <Script> de Next.js, pasar nonce={nonce}
      >
        {children}
      </body>
    </html>
  );
}
