# filepath: reports/mypy.ini
[mypy]
python_version = 3.12
strict = False           # Empezar sin strict para no romper todo
warn_return_any = True   # Avisar cuando se devuelve Any
warn_unused_imports = True
ignore_missing_imports = True  # Evitar errores en libs sin stubs

[mypy-psycopg2.*]
ignore_missing_imports = True

[mypy-structlog.*]
ignore_missing_imports = True

[mypy-flask_cors.*]
ignore_missing_imports = True