# filepath: (monitoring/alertmanager.yml)
route:
  receiver: 'slack-devops'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: 'slack-devops'
    slack_configs:
      - api_url: 'CAMBIAR_URL_ENV_VACIO'
        channel: '#devops-alerts'
        title: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        send_resolved: true